#!/usr/bin/env bash
# Installs ROS 2 Jazzy + Gazebo Harmonic + Nav2 for this project.
#
#   scripts/install_environment.sh apt        # official binaries (recommended on Ubuntu 24.04)
#   scripts/install_environment.sh robostack  # conda-forge/RoboStack build (no root apt repos needed)
#
# The robostack mode is what the reference development container used, because
# packages.ros.org / packages.osrfoundation.org were blocked by its network policy.
set -euo pipefail
MODE="${1:-apt}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

install_apt() {
  sudo apt-get update
  sudo apt-get install -y curl gnupg lsb-release software-properties-common
  sudo add-apt-repository -y universe
  sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
       -o /usr/share/keyrings/ros-archive-keyring.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] \
http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo "$UBUNTU_CODENAME") main" \
    | sudo tee /etc/apt/sources.list.d/ros2.list >/dev/null
  sudo apt-get update
  # ros-jazzy-ros-gz pulls in Gazebo Harmonic (the officially paired Gazebo for Jazzy).
  sudo apt-get install -y ros-jazzy-ros-base ros-jazzy-navigation2 ros-jazzy-nav2-bringup \
       ros-jazzy-ros-gz ros-jazzy-robot-state-publisher ros-jazzy-xacro ros-jazzy-rviz2 \
       python3-colcon-common-extensions python3-rosdep python3-pytest python3-matplotlib \
       python3-yaml xvfb mesa-utils
  sudo rosdep init 2>/dev/null || true
  rosdep update
  echo "Done. Use:  source /opt/ros/jazzy/setup.bash"
}

install_robostack() {
  local mm_dir="${MM_DIR:-/opt/mm}"
  export MAMBA_ROOT_PREFIX="${MAMBA_ROOT_PREFIX:-/opt/conda-root}"
  if [[ ! -x "${mm_dir}/bin/micromamba" ]]; then
    mkdir -p "${mm_dir}"
    curl -sSL https://conda.anaconda.org/conda-forge/linux-64/micromamba-2.9.0-0.tar.bz2 \
      | tar -xj -C "${mm_dir}" bin/micromamba
  fi
  "${mm_dir}/bin/micromamba" create -y -n ros_env -f "${REPO_ROOT}/env/robostack-jazzy.yml"
  # Software OpenGL + virtual display for machines without a GPU / monitor.
  if command -v apt-get >/dev/null; then
    apt-get install -y xvfb libegl-mesa0 libgl1-mesa-dri libglx-mesa0 mesa-utils || true
  fi
  cat > "${REPO_ROOT}/env/ros_env.sh" <<EOS
# Generated by scripts/install_environment.sh robostack
export MAMBA_ROOT_PREFIX=${MAMBA_ROOT_PREFIX}
eval "\$(${mm_dir}/bin/micromamba shell hook -s bash)"
micromamba activate ros_env
EOS
  echo "Done. Use:  source env/ros_env.sh"
}

case "${MODE}" in
  apt) install_apt ;;
  robostack) install_robostack ;;
  *) echo "unknown mode ${MODE} (use apt|robostack)"; exit 1 ;;
esac
